/**
 * Sudoers Management and Privilege Detection for Forge Linux Agent.
 *
 * Provides privilege level auditing, granular sudoers rule generation,
 * and safe installation to /etc/sudoers.d/forge with visudo syntax validation.
 */

import { execSync } from "node:child_process";
import { existsSync, unlinkSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import chalk from "chalk";

export interface PrivilegeStatus {
	isRoot: boolean;
	hasPasswordlessSudo: boolean;
	username: string;
	level: "root" | "sudo_nopasswd" | "unprivileged";
}

/**
 * Audit current user privilege level.
 */
export function checkPrivilegeLevel(): PrivilegeStatus {
	const isRoot = typeof process.getuid === "function" && process.getuid() === 0;
	const username = isRoot ? "root" : process.env.USER || process.env.LOGNAME || "forge";

	if (isRoot) {
		return {
			isRoot: true,
			hasPasswordlessSudo: true,
			username,
			level: "root",
		};
	}

	// Check if user has passwordless sudo via non-interactive sudo check
	let hasPasswordlessSudo = false;
	try {
		execSync("sudo -n true", { stdio: "ignore" });
		hasPasswordlessSudo = true;
	} catch {
		hasPasswordlessSudo = false;
	}

	return {
		isRoot: false,
		hasPasswordlessSudo,
		username,
		level: hasPasswordlessSudo ? "sudo_nopasswd" : "unprivileged",
	};
}

/**
 * Standard sysadmin command binaries for granular sudoers whitelisting.
 */
export const GRANULAR_SYSADMIN_COMMANDS = [
	"/usr/bin/systemctl status *",
	"/usr/bin/systemctl restart *",
	"/usr/bin/systemctl reload *",
	"/usr/bin/systemctl start *",
	"/usr/bin/systemctl stop *",
	"/usr/bin/systemctl is-active *",
	"/usr/bin/journalctl *",
	"/usr/sbin/ss *",
	"/usr/bin/ss *",
	"/usr/bin/docker *",
	"/usr/bin/podman *",
	"/usr/bin/lsof *",
	"/usr/bin/df *",
	"/usr/bin/free *",
	"/usr/bin/dmesg *",
	"/usr/bin/cat /var/log/*",
	"/usr/bin/tail /var/log/*",
	"/usr/bin/head /var/log/*",
	"/usr/bin/grep * /var/log/*",
	"/usr/bin/find /var/log/*",
	"/usr/sbin/nginx -t",
	"/usr/sbin/sshd -t",
];

/**
 * Generate sudoers file content for the given username.
 */
export function generateSudoersConfig(options: { username?: string; mode?: "granular" | "full" } = {}): string {
	const user = options.username || process.env.USER || process.env.LOGNAME || "forge";
	const mode = options.mode || "granular";

	if (mode === "full") {
		return `# /etc/sudoers.d/forge - Full sudo privileges for Forge Autonomous Agent
# Generated by Forge CLI on ${new Date().toISOString()}

${user} ALL=(ALL) NOPASSWD: ALL
`;
	}

	const commandList = GRANULAR_SYSADMIN_COMMANDS.join(", \\\n    ");

	return `# /etc/sudoers.d/forge - Granular sysadmin sudo privileges for Forge Autonomous Agent
# Generated by Forge CLI on ${new Date().toISOString()}

${user} ALL=(ALL) NOPASSWD: \\
    ${commandList}
`;
}

/**
 * Safely install sudoers file using visudo syntax validation.
 */
export function installSudoersFile(
	content: string,
	targetPath = "/etc/sudoers.d/forge",
): { installed: boolean; path: string; error?: string } {
	const tmpPath = join(homedir(), `.forge-sudoers-${Date.now()}`);

	try {
		// 1. Write to temporary file
		writeFileSync(tmpPath, content, { mode: 0o440 });

		// 2. Validate syntax with visudo if available
		try {
			execSync(`visudo -cf ${tmpPath}`, { stdio: "pipe" });
		} catch (err: any) {
			const errMsg = err.stderr ? err.stderr.toString() : err.message;
			return { installed: false, path: targetPath, error: `visudo syntax error: ${errMsg}` };
		}

		// 3. Move into /etc/sudoers.d (using sudo if not root)
		const isRoot = typeof process.getuid === "function" && process.getuid() === 0;
		const cpCmd = isRoot
			? `cp ${tmpPath} ${targetPath} && chmod 0440 ${targetPath}`
			: `sudo -n cp ${tmpPath} ${targetPath} && sudo -n chmod 0440 ${targetPath}`;

		execSync(cpCmd, { stdio: "pipe" });
		return { installed: true, path: targetPath };
	} catch (err: any) {
		return {
			installed: false,
			path: targetPath,
			error: err.message || "Failed to write to /etc/sudoers.d/forge (requires root or sudo)",
		};
	} finally {
		if (existsSync(tmpPath)) {
			try {
				unlinkSync(tmpPath);
			} catch {}
		}
	}
}

/**
 * CLI subcommand handler for `forge task sudoers` / `forge system sudoers`.
 */
export async function handleSudoersCommand(args: string[]): Promise<void> {
	const action = args[0] || "show";
	const isFull = args.includes("--full");
	const mode = isFull ? "full" : "granular";

	if (action === "check" || action === "status") {
		const priv = checkPrivilegeLevel();
		console.log();
		console.log(chalk.bold("Forge Privilege Status:"));
		console.log(`  User:                 ${chalk.cyan(priv.username)}`);
		console.log(`  Root (UID 0):         ${priv.isRoot ? chalk.green("YES") : chalk.yellow("NO")}`);
		console.log(
			`  Passwordless Sudo:    ${priv.hasPasswordlessSudo ? chalk.green("ENABLED") : chalk.red("DISABLED")}`,
		);
		console.log(`  Operational Level:    ${chalk.bold.magenta(priv.level.toUpperCase())}`);
		console.log();

		if (priv.level === "unprivileged") {
			console.log(chalk.yellow("⚠️  Tasks requiring root privileges will fail without passwordless sudo."));
			console.log(
				chalk.dim('To generate sudoers config: "forge task sudoers show" or "sudo forge task sudoers install"'),
			);
		} else {
			console.log(chalk.green("✓ Host is configured to execute elevated and sysadmin tasks."));
		}
		return;
	}

	if (action === "install") {
		const content = generateSudoersConfig({ mode });
		const result = installSudoersFile(content);

		if (result.installed) {
			console.log(chalk.green(`✓ Installed sudoers configuration to ${result.path}`));
			console.log(chalk.dim("Privileges verified via visudo syntax check."));
		} else {
			console.error(chalk.red(`✕ Failed to install sudoers file: ${result.error}`));
			console.log();
			console.log(chalk.dim("To install manually:"));
			console.log(chalk.cyan(`sudo tee /etc/sudoers.d/forge << 'EOF'\n${content}EOF`));
			console.log(chalk.dim("sudo chmod 0440 /etc/sudoers.d/forge"));
			process.exitCode = 1;
		}
		return;
	}

	// Default: show
	const priv = checkPrivilegeLevel();
	const content = generateSudoersConfig({ username: priv.username, mode });

	console.log();
	console.log(chalk.bold.cyan("┌────────────────────────────────────────────────────────┐"));
	console.log(chalk.bold.cyan("│             FORGE SUDOERS CONFIGURATION                │"));
	console.log(chalk.bold.cyan("│    Enable non-interactive sysadmin background tasks    │"));
	console.log(chalk.bold.cyan("└────────────────────────────────────────────────────────┘"));
	console.log();
	console.log(`  Target User: ${chalk.bold.green(priv.username)}`);
	console.log(`  Mode:        ${chalk.bold(mode)} (${isFull ? "All commands" : "Whitelisted sysadmin commands"})`);
	console.log(`  Destination: ${chalk.bold("/etc/sudoers.d/forge")}`);
	console.log();
	console.log(chalk.bold("Recommended File Content:"));
	console.log(chalk.dim("─────────────────────────────────────────────────────────────"));
	console.log(chalk.green(content));
	console.log(chalk.dim("─────────────────────────────────────────────────────────────"));
	console.log();
	console.log(chalk.bold("How to Apply:"));
	console.log(
		`  ${chalk.cyan("sudo forge task sudoers install")}               ${chalk.dim("# Install automatically")}`,
	);
	console.log(
		`  ${chalk.cyan("sudo forge task sudoers install --full")}        ${chalk.dim("# Install full sudoers")}`,
	);
	console.log(
		`  ${chalk.cyan("forge task sudoers check")}                      ${chalk.dim("# Verify privilege status")}`,
	);
}
